"""add payer fields

Revision ID: 556f244f40e0
Revises: d94b20e9a2c0
Create Date: 2024-12-21 15:53:12.775583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556f244f40e0'
down_revision = 'd94b20e9a2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('payer_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('payer_id')
        batch_op.drop_column('payer_email')

    # ### end Alembic commands ###
