"""add payer phone

Revision ID: 7fe3ecbb5ecb
Revises: 556f244f40e0
Create Date: 2024-12-21 15:56:15.733589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe3ecbb5ecb'
down_revision = '556f244f40e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('payer_phone')

    # ### end Alembic commands ###
